GET http://localhost:8000/api/roles

###
GET http://localhost:8000/api/employees

###
GET http://localhost:8000/api/classes

###
GET http://localhost:8000/api/students

###
GET http://localhost:8000/api/teachers

###
GET http://localhost:8000/api/subjects

###
GET http://localhost:8000/api/users

###
GET http://localhost:8000/api/userroles

###
GET http://localhost:8000/api/profile/2

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "username": "P00123456",
  "password": "P00123456",
  "status": "Aktif"
}